body:
  - type: textBlock
    attributes:
      description: Thank you for using rtfm. Due to limits with flow and the way this plugin was written, I am unable to put the plugin settings in this settings menu. By default, the settings keyword is "rtfm". Using this keyword, you can open up the settings menu.