name: Build Plugin

on:
    push:
        branches: [main]
    release:
        types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.13.1
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'

      - run: echo ${{steps.version.outputs.prop}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt -t ./lib
      
      - name: Build Archive
        run: |
          python build_plugin.py ${{ github.event.repository.name }}.zip
    
      - name: Upload Archive to workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.event.repository.name }}.zip
          name: ${{ github.event.repository.name }}.zip

      - name: Upload Archive to release artifacts
        uses: softprops/action-gh-release@v2
        if: ${{ github.event_name == 'release' }}
        with:
            files: ${{ github.event.repository.name }}.zip