name: Build Plugin

on:
    push:
        branches: [main]
    release:
        types: [published]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.11.4
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: cibere/FlowBuildPluginAction@master
        with:
          discord_webhook_url: ${{ secrets.DISCORD_BUILD_WEBHOOK }}
          dirs: plugin,assets
          files: main.py