name: Build Docs

on:
  push:
    branches:
        - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      python_ver: 3.11
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ env.python_ver }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python_ver }}

      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
          path: 'plugin.json'
          prop_path: 'Version'

      - run: echo ${{steps.version.outputs.prop}}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install -r ./docs/requirements.txt
          pip install -r ./.github/ci/requirements.txt

      - name: Build Docs
        id: build-docs
        run: |
            cd docs
            sphinx-build -b html -j auto -a -n -T -W --keep-going . _build/${{steps.version.outputs.prop}}
      
      - name: Move Build
        id: move-doc-build
        if: ${{ always() && steps.build-docs.outcome == 'success' }}
        run: |
          cd .github
          cd ci
          python move_doc_builds.py
        
      - name: Update Index
        run: |
          cd .github
          cd ci
          python index_updater.py

      - name: Commit Changes
        if: ${{ always() && steps.move-doc-build.outcome == 'success' }}
        run: |
          git fetch
          git checkout -f gh-pages
          git add .
          git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "Auto update docs" --author="cibere <71997063+cibere@users.noreply.github.com>" --allow-empty
          git push