name: Ruff

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]

    name: Lint on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          pip install -r requirements.txt

      - name: Run Ruff Linter
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        uses: astral-sh/ruff-action@v3

  format:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]

    name: Format on ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up CPython ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: install-deps
        run: |
          pip install -r requirements.txt
          pip install ruff
      
      - name: Run Ruff Formatter
        if: ${{ always() && steps.install-deps.outcome == 'success' }}
        run: |
            ruff format --check
