name: Run Tests

on:
    push:
    pull_request:
      types: [opened, reopened, synchronize]  

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.11', '3.12', '3.13' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install -r ./tests/requirements.txt
      
      - name: Run Tests
        run: |
          python -m pytest --dump

      - name: Upload Cache to workflow artifacts
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          path: caches
          name: cache-${{ matrix.python-version }}