name: Test Workflow

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    name: testy
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: test git
        run: git